runtime: go111

handlers:
- url: /styles
  static_dir: css
- url: /images
  static_dir: images
- url: /templates
  static_dir: templates

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto